#!/bin/bash
# Quick Deploy Instructions for SummitIQ
# Run these commands on your LOCAL machine

echo "🚀 SummitIQ - Deploy to Production"
echo "===================================="
echo ""
echo "📋 Step-by-Step Deployment:"
echo ""
echo "1️⃣  Clone/Pull the latest code:"
echo "    git clone https://github.com/ContractPlan-Inc/summitiq.git"
echo "    cd summitiq"
echo "    git checkout claude/audit-repo-findings-fixes-011CUthe7N5P4FDKPMg1zsL9"
echo ""
echo "2️⃣  Install dependencies:"
echo "    npm install"
echo ""
echo "3️⃣  Install Vercel CLI (if not already installed):"
echo "    npm install -g vercel"
echo ""
echo "4️⃣  Login to Vercel:"
echo "    vercel login"
echo "    (This will open your browser - sign in with GitHub/Email)"
echo ""
echo "5️⃣  Deploy to production:"
echo "    vercel --prod"
echo ""
echo "✅ Your app will be live in ~90 seconds!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 Expected URL: https://summitiq.vercel.app"
echo ""
echo "📊 What you'll see:"
echo "   • Uploading files..."
echo "   • Building production bundle..."
echo "   • Deploying to edge network..."
echo "   • ✅ Production: https://summitiq.vercel.app"
echo ""
echo "⚡ That's it! Your world-class app is live!"
echo ""
